import { OBJECTION_REASON_STATUTES } from './constants';
import type { SmsOwnerLanguage } from './smsPreview';
import type { ParcelObjection } from './types';

// Step 65 — printable content for a filed objection's formal legal-filing
// document (the QR-stamped record generated after "Submit an Objection" on
// the landowner status page). Kept self-contained, same reason as
// `noticeContent.ts`: it must be addressable by the owner's own
// `preferredLanguage` independent of the signed-in official's UI language,
// and living in `translations.ts` would create a circular import through
// `domain/index.ts`.
export type LegalFilingParams = {
  surveyNumber: string;
  village: string;
  tehsil: string;
  district: string;
  submittedOn: string;
  submittedBy: string;
  description: string;
};

export type LegalFilingLabels = {
  officeHeader: string;
  filingTitle: string;
  ownerLabel: string;
  surveyLabel: string;
  villageLabel: string;
  tehsilLabel: string;
  districtLabel: string;
  groundLabel: string;
  citationLabel: string;
  filedOnLabel: string;
  descriptionLabel: string;
  qrCaption: string;
  signatureLabel: string;
  classifierNote: string;
  disclaimer: string;
};

const LABELS: Record<SmsOwnerLanguage, LegalFilingLabels> = {
  en: {
    officeHeader: 'Office of the District Collector',
    filingTitle: 'Objection Filed under Section 15, LARR 2013',
    ownerLabel: 'Filed by',
    surveyLabel: 'Survey No.',
    villageLabel: 'Village',
    tehsilLabel: 'Tehsil',
    districtLabel: 'District',
    groundLabel: 'Statutory ground',
    citationLabel: 'Citation',
    filedOnLabel: 'Filed on',
    descriptionLabel: 'Objection as recorded',
    qrCaption: 'Scan this code to view the case status online',
    signatureLabel: 'Received by (Land Acquisition Officer, signature & seal)',
    classifierNote:
      'The statutory ground shown above was suggested by a closed keyword classifier from the objector’s own words and confirmed by them before filing. It routes the filing category only; it does not decide the objection’s merits.',
    disclaimer:
      'Generated by the BhoomiSetu prototype for demonstration. Verify all details against the official case record before relying on it.',
  },
  hi: {
    officeHeader: 'जिला कलेक्टर कार्यालय',
    filingTitle: 'धारा 15, LARR 2013 के अंतर्गत दर्ज आपत्ति',
    ownerLabel: 'दर्ज करने वाला',
    surveyLabel: 'सर्वे नंबर',
    villageLabel: 'गाँव',
    tehsilLabel: 'तहसील',
    districtLabel: 'जिला',
    groundLabel: 'वैधानिक आधार',
    citationLabel: 'उद्धरण',
    filedOnLabel: 'दर्ज करने की तिथि',
    descriptionLabel: 'दर्ज की गई आपत्ति',
    qrCaption: 'मामले की स्थिति ऑनलाइन देखने के लिए इस कोड को स्कैन करें',
    signatureLabel: 'प्राप्तकर्ता (भूमि अधिग्रहण अधिकारी, हस्ताक्षर एवं मुहर)',
    classifierNote:
      'ऊपर दिखाया गया वैधानिक आधार आपत्तिकर्ता के अपने शब्दों से एक बंद कीवर्ड वर्गीकारक द्वारा सुझाया गया था और दर्ज करने से पहले उनके द्वारा पुष्टि किया गया था। यह केवल फाइलिंग श्रेणी तय करता है; यह आपत्ति के गुण-दोष का निर्णय नहीं करता।',
    disclaimer:
      'यह BhoomiSetu प्रोटोटाइप द्वारा प्रदर्शन हेतु तैयार किया गया है। भरोसा करने से पहले सभी विवरण आधिकारिक अभिलेख से सत्यापित करें।',
  },
  mr: {
    officeHeader: 'जिल्हाधिकारी कार्यालय',
    filingTitle: 'कलम 15, LARR 2013 अंतर्गत दाखल आक्षेप',
    ownerLabel: 'दाखल करणारे',
    surveyLabel: 'सर्वे क्रमांक',
    villageLabel: 'गाव',
    tehsilLabel: 'तालुका',
    districtLabel: 'जिल्हा',
    groundLabel: 'वैधानिक आधार',
    citationLabel: 'उद्धरण',
    filedOnLabel: 'दाखल तारीख',
    descriptionLabel: 'नोंदवलेला आक्षेप',
    qrCaption: 'प्रकरणाची स्थिती ऑनलाइन पाहण्यासाठी हा कोड स्कॅन करा',
    signatureLabel: 'प्राप्तकर्ता (भूमि संपादन अधिकारी, स्वाक्षरी व शिक्का)',
    classifierNote:
      'वरील वैधानिक आधार आक्षेपकर्त्याच्या स्वतःच्या शब्दांवरून एका बंद कीवर्ड वर्गीकरणाद्वारे सुचवला गेला आणि दाखल करण्यापूर्वी त्यांनी पुष्टी केली. हे केवळ दाखल श्रेणी ठरवते; ते आक्षेपाच्या गुणवत्तेवर निर्णय देत नाही.',
    disclaimer:
      'हे BhoomiSetu प्रोटोटाइपद्वारे प्रात्यक्षिकासाठी तयार केले आहे. विश्वास ठेवण्यापूर्वी सर्व तपशील अधिकृत नोंदीशी पडताळून पाहा.',
  },
  gu: {
    officeHeader: 'જિલ્લા કલેક્ટર કચેરી',
    filingTitle: 'કલમ 15, LARR 2013 હેઠળ દાખલ કરેલો વાંધો',
    ownerLabel: 'દાખલ કરનાર',
    surveyLabel: 'સર્વે નંબર',
    villageLabel: 'ગામ',
    tehsilLabel: 'તાલુકો',
    districtLabel: 'જિલ્લો',
    groundLabel: 'વૈધાનિક આધાર',
    citationLabel: 'સંદર્ભ',
    filedOnLabel: 'દાખલ તારીખ',
    descriptionLabel: 'નોંધાયેલો વાંધો',
    qrCaption: 'કેસની સ્થિતિ ઓનલાઇન જોવા માટે આ કોડ સ્કેન કરો',
    signatureLabel: 'સ્વીકારનાર (ભૂમિ સંપાદન અધિકારી, સહી અને સિક્કો)',
    classifierNote:
      'ઉપર દર્શાવેલ વૈધાનિક આધાર વાંધો ઉઠાવનારના પોતાના શબ્દો પરથી એક બંધ કીવર્ડ વર્ગીકારક દ્વારા સૂચવવામાં આવ્યો હતો અને દાખલ કરતા પહેલા તેમના દ્વારા પુષ્ટિ કરવામાં આવ્યો હતો. તે ફક્ત ફાઇલિંગ કેટેગરી નક્કી કરે છે; તે વાંધાના ગુણદોષનો નિર્ણય કરતું નથી.',
    disclaimer:
      'આ BhoomiSetu પ્રોટોટાઇપ દ્વારા નિદર્શન માટે બનાવવામાં આવ્યું છે. વિશ્વાસ કરતા પહેલા બધી વિગતો સત્તાવાર રેકોર્ડ સાથે ચકાસો.',
  },
  te: {
    officeHeader: 'జిల్లా కలెక్టర్ కార్యాలయం',
    filingTitle: 'సెక్షన్ 15, LARR 2013 కింద దాఖలైన అభ్యంతరం',
    ownerLabel: 'దాఖలు చేసినవారు',
    surveyLabel: 'సర్వే నంబర్',
    villageLabel: 'గ్రామం',
    tehsilLabel: 'తహసీల్',
    districtLabel: 'జిల్లా',
    groundLabel: 'చట్టబద్ధ కారణం',
    citationLabel: 'ఉదాహరణ',
    filedOnLabel: 'దాఖలు తేదీ',
    descriptionLabel: 'నమోదైన అభ్యంతరం',
    qrCaption: 'కేసు స్థితిని ఆన్‌లైన్‌లో చూడటానికి ఈ కోడ్‌ను స్కాన్ చేయండి',
    signatureLabel: 'స్వీకరించినవారు (భూసేకరణ అధికారి, సంతకం మరియు ముద్ర)',
    classifierNote:
      'పైన చూపిన చట్టబద్ధ కారణం అభ్యంతరదారుడి స్వంత మాటల నుండి ఒక క్లోజ్డ్ కీవర్డ్ వర్గీకరణి ద్వారా సూచించబడింది మరియు దాఖలు చేసే ముందు వారిచే నిర్ధారించబడింది. ఇది ఫైలింగ్ వర్గాన్ని మాత్రమే నిర్ణయిస్తుంది; ఇది అభ్యంతరం యొక్క గుణదోషాలను నిర్ణయించదు.',
    disclaimer:
      'ఇది ప్రదర్శన కోసం BhoomiSetu ప్రోటోటైప్ ద్వారా రూపొందించబడింది. ఆధారపడే ముందు అన్ని వివరాలను అధికారిక రికార్డుతో ధృవీకరించండి.',
  },
  ta: {
    officeHeader: 'மாவட்ட ஆட்சியர் அலுவலகம்',
    filingTitle: 'பிரிவு 15, LARR 2013-ன் கீழ் பதிவு செய்யப்பட்ட எதிர்ப்பு',
    ownerLabel: 'பதிவு செய்தவர்',
    surveyLabel: 'சர்வே எண்',
    villageLabel: 'கிராமம்',
    tehsilLabel: 'தாலுகா',
    districtLabel: 'மாவட்டம்',
    groundLabel: 'சட்டப்பூர்வ காரணம்',
    citationLabel: 'மேற்கோள்',
    filedOnLabel: 'பதிவு செய்த தேதி',
    descriptionLabel: 'பதிவு செய்யப்பட்ட எதிர்ப்பு',
    qrCaption: 'வழக்கின் நிலையை ஆன்லைனில் காண இந்த குறியீட்டை ஸ்கேன் செய்யவும்',
    signatureLabel: 'பெற்றவர் (நில கையகப்படுத்தல் அதிகாரி, கையொப்பம் மற்றும் முத்திரை)',
    classifierNote:
      'மேலே காட்டப்பட்ட சட்டப்பூர்வ காரணம் எதிர்ப்பாளரின் சொந்த வார்த்தைகளிலிருந்து ஒரு மூடிய முக்கிய-சொல் வகைப்படுத்தி மூலம் பரிந்துரைக்கப்பட்டு, பதிவு செய்வதற்கு முன் அவரால் உறுதிப்படுத்தப்பட்டது. இது பதிவு வகையை மட்டுமே நிர்ணயிக்கிறது; இது எதிர்ப்பின் தகுதியை தீர்மானிக்காது.',
    disclaimer:
      'இது காட்சிக்காக BhoomiSetu முன்மாதிரி மூலம் உருவாக்கப்பட்டது. நம்பிக்கை வைப்பதற்கு முன் அனைத்து விவரங்களையும் அதிகாரப்பூர்வ பதிவுடன் சரிபார்க்கவும்.',
  },
  kn: {
    officeHeader: 'ಜಿಲ್ಲಾಧಿಕಾರಿ ಕಚೇರಿ',
    filingTitle: 'ಸೆಕ್ಷನ್ 15, LARR 2013ರ ಅಡಿಯಲ್ಲಿ ಸಲ್ಲಿಸಿದ ಆಕ್ಷೇಪಣೆ',
    ownerLabel: 'ಸಲ್ಲಿಸಿದವರು',
    surveyLabel: 'ಸರ್ವೆ ಸಂಖ್ಯೆ',
    villageLabel: 'ಗ್ರಾಮ',
    tehsilLabel: 'ತಾಲೂಕು',
    districtLabel: 'ಜಿಲ್ಲೆ',
    groundLabel: 'ಶಾಸನಬದ್ಧ ಕಾರಣ',
    citationLabel: 'ಉಲ್ಲೇಖ',
    filedOnLabel: 'ಸಲ್ಲಿಸಿದ ದಿನಾಂಕ',
    descriptionLabel: 'ದಾಖಲಾದ ಆಕ್ಷೇಪಣೆ',
    qrCaption: 'ಪ್ರಕರಣದ ಸ್ಥಿತಿಯನ್ನು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ವೀಕ್ಷಿಸಲು ಈ ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    signatureLabel: 'ಸ್ವೀಕರಿಸಿದವರು (ಭೂ ಸ್ವಾಧೀನ ಅಧಿಕಾರಿ, ಸಹಿ ಮತ್ತು ಮುದ್ರೆ)',
    classifierNote:
      'ಮೇಲೆ ತೋರಿಸಿದ ಶಾಸನಬದ್ಧ ಕಾರಣವನ್ನು ಆಕ್ಷೇಪಣೆದಾರರ ಸ್ವಂತ ಮಾತುಗಳಿಂದ ಒಂದು ಮುಚ್ಚಿದ ಕೀವರ್ಡ್ ವರ್ಗೀಕಾರಕ ಸೂಚಿಸಿತು ಮತ್ತು ಸಲ್ಲಿಸುವ ಮೊದಲು ಅವರು ದೃಢಪಡಿಸಿದರು. ಇದು ಸಲ್ಲಿಕೆ ವರ್ಗವನ್ನು ಮಾತ್ರ ನಿರ್ಧರಿಸುತ್ತದೆ; ಇದು ಆಕ್ಷೇಪಣೆಯ ಅರ್ಹತೆಯನ್ನು ನಿರ್ಧರಿಸುವುದಿಲ್ಲ.',
    disclaimer:
      'ಇದನ್ನು ಪ್ರದರ್ಶನಕ್ಕಾಗಿ BhoomiSetu ಪ್ರೋಟೋಟೈಪ್ ಮೂಲಕ ರಚಿಸಲಾಗಿದೆ. ಅವಲಂಬಿಸುವ ಮೊದಲು ಎಲ್ಲಾ ವಿವರಗಳನ್ನು ಅಧಿಕೃತ ದಾಖಲೆಯೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿ.',
  },
  bn: {
    officeHeader: 'জেলা কালেক্টর কার্যালয়',
    filingTitle: 'ধারা ১৫, LARR ২০১৩ অনুযায়ী দাখিলকৃত আপত্তি',
    ownerLabel: 'দাখিলকারী',
    surveyLabel: 'সার্ভে নম্বর',
    villageLabel: 'গ্রাম',
    tehsilLabel: 'তহশিল',
    districtLabel: 'জেলা',
    groundLabel: 'বিধিবদ্ধ কারণ',
    citationLabel: 'উদ্ধৃতি',
    filedOnLabel: 'দাখিলের তারিখ',
    descriptionLabel: 'নথিভুক্ত আপত্তি',
    qrCaption: 'মামলার অবস্থা অনলাইনে দেখতে এই কোডটি স্ক্যান করুন',
    signatureLabel: 'গ্রহণকারী (ভূমি অধিগ্রহণ কর্মকর্তা, স্বাক্ষর ও সিল)',
    classifierNote:
      'উপরে দেখানো বিধিবদ্ধ কারণটি আপত্তিকারীর নিজের কথা থেকে একটি বদ্ধ কীওয়ার্ড শ্রেণীবিন্যাসকারী দ্বারা প্রস্তাবিত হয়েছিল এবং দাখিলের আগে তাদের দ্বারা নিশ্চিত করা হয়েছিল। এটি কেবল দাখিলের বিভাগ নির্ধারণ করে; এটি আপত্তির যোগ্যতা নির্ধারণ করে না।',
    disclaimer:
      'এটি প্রদর্শনের জন্য BhoomiSetu প্রোটোটাইপ দ্বারা তৈরি করা হয়েছে। নির্ভর করার আগে সমস্ত বিবরণ সরকারি রেকর্ডের সাথে যাচাই করুন।',
  },
  or: {
    officeHeader: 'ଜିଲ୍ଲା କାଲେକ୍ଟର କାର୍ଯ୍ୟାଳୟ',
    filingTitle: 'ଧାରା 15, LARR 2013 ଅନୁଯାୟୀ ଦାଖଲ ହୋଇଥିବା ଆପତ୍ତି',
    ownerLabel: 'ଦାଖଲକାରୀ',
    surveyLabel: 'ସର୍ଭେ ନମ୍ବର',
    villageLabel: 'ଗାଁ',
    tehsilLabel: 'ତହସିଲ',
    districtLabel: 'ଜିଲ୍ଲା',
    groundLabel: 'ବିଧିବଦ୍ଧ କାରଣ',
    citationLabel: 'ଉଦ୍ଧୃତି',
    filedOnLabel: 'ଦାଖଲ ତାରିଖ',
    descriptionLabel: 'ଲିପିବଦ୍ଧ ଆପତ୍ତି',
    qrCaption: 'କେସର ସ୍ଥିତି ଅନଲାଇନରେ ଦେଖିବାକୁ ଏହି କୋଡ୍ ସ୍କାନ୍ କରନ୍ତୁ',
    signatureLabel: 'ଗ୍ରହଣକାରୀ (ଭୂମି ଅଧିଗ୍ରହଣ ଅଧିକାରୀ, ହସ୍ତାକ୍ଷର ଏବଂ ମୋହର)',
    classifierNote:
      'ଉପରେ ଦର୍ଶାଯାଇଥିବା ବିଧିବଦ୍ଧ କାରଣ ଆପତ୍ତିକାରୀଙ୍କ ନିଜ ଶବ୍ଦରୁ ଏକ ବନ୍ଦ କୀୱାର୍ଡ ବର୍ଗୀକରଣ ଦ୍ୱାରା ପ୍ରସ୍ତାବିତ ହୋଇଥିଲା ଏବଂ ଦାଖଲ କରିବା ପୂର୍ବରୁ ସେମାନଙ୍କ ଦ୍ୱାରା ନିଶ୍ଚିତ ହୋଇଥିଲା। ଏହା କେବଳ ଦାଖଲ ବର୍ଗକୁ ସ୍ଥିର କରେ; ଏହା ଆପତ୍ତିର ଗୁଣାଗୁଣ ନିର୍ଣ୍ଣୟ କରେ ନାହିଁ।',
    disclaimer:
      'ଏହା ପ୍ରଦର୍ଶନ ପାଇଁ BhoomiSetu ପ୍ରୋଟୋଟାଇପ୍ ଦ୍ୱାରା ତିଆରି ହୋଇଛି। ନିର୍ଭର କରିବା ପୂର୍ବରୁ ସମସ୍ତ ବିବରଣୀ ସରକାରୀ ରେକର୍ଡ ସହିତ ଯାଞ୍ଚ କରନ୍ତୁ।',
  },
  pa: {
    officeHeader: 'ਜ਼ਿਲ੍ਹਾ ਕਲੈਕਟਰ ਦਫ਼ਤਰ',
    filingTitle: 'ਧਾਰਾ 15, LARR 2013 ਅਧੀਨ ਦਰਜ ਇਤਰਾਜ਼',
    ownerLabel: 'ਦਰਜ ਕਰਨ ਵਾਲਾ',
    surveyLabel: 'ਸਰਵੇ ਨੰਬਰ',
    villageLabel: 'ਪਿੰਡ',
    tehsilLabel: 'ਤਹਿਸੀਲ',
    districtLabel: 'ਜ਼ਿਲ੍ਹਾ',
    groundLabel: 'ਵਿਧਾਨਕ ਆਧਾਰ',
    citationLabel: 'ਹਵਾਲਾ',
    filedOnLabel: 'ਦਰਜ ਮਿਤੀ',
    descriptionLabel: 'ਦਰਜ ਕੀਤਾ ਇਤਰਾਜ਼',
    qrCaption: 'ਕੇਸ ਦੀ ਸਥਿਤੀ ਆਨਲਾਈਨ ਵੇਖਣ ਲਈ ਇਹ ਕੋਡ ਸਕੈਨ ਕਰੋ',
    signatureLabel: 'ਪ੍ਰਾਪਤ ਕਰਨ ਵਾਲਾ (ਭੂਮੀ ਗ੍ਰਹਿਣ ਅਧਿਕਾਰੀ, ਦਸਤਖਤ ਅਤੇ ਮੋਹਰ)',
    classifierNote:
      'ਉੱਪਰ ਦਿਖਾਇਆ ਗਿਆ ਵਿਧਾਨਕ ਆਧਾਰ ਇਤਰਾਜ਼ਕਰਤਾ ਦੇ ਆਪਣੇ ਸ਼ਬਦਾਂ ਤੋਂ ਇੱਕ ਬੰਦ ਕੀਵਰਡ ਵਰਗੀਕਰਤਾ ਦੁਆਰਾ ਸੁਝਾਇਆ ਗਿਆ ਸੀ ਅਤੇ ਦਰਜ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਉਹਨਾਂ ਦੁਆਰਾ ਪੁਸ਼ਟੀ ਕੀਤਾ ਗਿਆ ਸੀ। ਇਹ ਸਿਰਫ਼ ਦਰਜ ਕਰਨ ਦੀ ਸ਼੍ਰੇਣੀ ਤੈਅ ਕਰਦਾ ਹੈ; ਇਹ ਇਤਰਾਜ਼ ਦੇ ਗੁਣ-ਦੋਸ਼ ਦਾ ਫੈਸਲਾ ਨਹੀਂ ਕਰਦਾ।',
    disclaimer:
      'ਇਹ ਪ੍ਰਦਰਸ਼ਨ ਲਈ BhoomiSetu ਪ੍ਰੋਟੋਟਾਈਪ ਦੁਆਰਾ ਤਿਆਰ ਕੀਤਾ ਗਿਆ ਹੈ। ਭਰੋਸਾ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਸਾਰੇ ਵੇਰਵਿਆਂ ਦੀ ਅਧਿਕਾਰਤ ਰਿਕਾਰਡ ਨਾਲ ਪੁਸ਼ਟੀ ਕਰੋ।',
  },
};

export type ObjectionFilingContent = {
  labels: LegalFilingLabels;
  title: string;
  groundLabel: string;
  citation: string;
  params: LegalFilingParams;
};

// Builds the printable filed-objection document's translated labels, title,
// statute citation and field values for the given owner language —
// deterministic, no network call, same discipline as
// `buildNoticeContent`/`buildSmsPreview`. `groundLabel` is passed in by the
// caller (looked up from the already-i18n-aware `objectionReasonLabels`)
// rather than duplicated in this module's own label set.
export function buildObjectionFilingContent(
  objection: ParcelObjection,
  groundLabel: string,
  params: LegalFilingParams,
  language: SmsOwnerLanguage,
): ObjectionFilingContent {
  const labels = LABELS[language];
  return {
    labels,
    title: labels.filingTitle,
    groundLabel,
    citation: OBJECTION_REASON_STATUTES[objection.reason],
    params,
  };
}
