import type { SmsOwnerLanguage } from './smsPreview';

// Step 54 — printable statutory-notice content for the landowner-facing QR
// notice. Kept self-contained (not imported from `src/i18n/translations.ts`)
// for the same reason as `smsPreview.ts`: it must be addressable by the
// owner's own `preferredLanguage`, independent of whichever UI language the
// signed-in official currently has selected, and pulling it into
// `translations.ts` would create a circular import through `domain/index.ts`.
export type NoticeType = 'section_11' | 'award';

export type NoticeParams = {
  projectName: string;
  surveyNumber: string;
  village: string;
  tehsil: string;
  district: string;
  compensationEstimateText: string;
  compensationPaidText: string;
  referenceDate: string;
};

export type NoticeLabels = {
  officeHeader: string;
  section11Title: string;
  awardTitle: string;
  ownerLabel: string;
  surveyLabel: string;
  villageLabel: string;
  tehsilLabel: string;
  districtLabel: string;
  projectLabel: string;
  areaLabel: string;
  compensationAssessedLabel: string;
  compensationPaidLabel: string;
  dateLabel: string;
  qrCaption: string;
  signatureLabel: string;
  disclaimer: string;
};

type BodyTemplate = (params: NoticeParams) => string;

const LABELS: Record<SmsOwnerLanguage, NoticeLabels> = {
  en: {
    officeHeader: 'Office of the District Collector',
    section11Title: 'Notification under Section 11',
    awardTitle: 'Award Intimation',
    ownerLabel: 'Owner',
    surveyLabel: 'Survey No.',
    villageLabel: 'Village',
    tehsilLabel: 'Tehsil',
    districtLabel: 'District',
    projectLabel: 'Project',
    areaLabel: 'Area',
    compensationAssessedLabel: 'Compensation Assessed',
    compensationPaidLabel: 'Compensation Paid',
    dateLabel: 'Date',
    qrCaption: 'Scan this code to view your case status online',
    signatureLabel: 'Signature & Seal of Issuing Officer',
    disclaimer:
      'Generated by the BhoomiSetu prototype for demonstration. Verify all details against the official case record before relying on it.',
  },
  hi: {
    officeHeader: 'जिला कलेक्टर कार्यालय',
    section11Title: 'धारा 11 के अंतर्गत अधिसूचना',
    awardTitle: 'पुरस्कार सूचना',
    ownerLabel: 'मालिक',
    surveyLabel: 'सर्वे नंबर',
    villageLabel: 'गाँव',
    tehsilLabel: 'तहसील',
    districtLabel: 'जिला',
    projectLabel: 'परियोजना',
    areaLabel: 'क्षेत्रफल',
    compensationAssessedLabel: 'आकलित मुआवज़ा',
    compensationPaidLabel: 'भुगतान किया गया मुआवज़ा',
    dateLabel: 'दिनांक',
    qrCaption: 'अपने मामले की स्थिति ऑनलाइन देखने के लिए इस कोड को स्कैन करें',
    signatureLabel: 'जारीकर्ता अधिकारी के हस्ताक्षर एवं मुहर',
    disclaimer:
      'यह BhoomiSetu प्रोटोटाइप द्वारा प्रदर्शन हेतु तैयार किया गया है। भरोसा करने से पहले सभी विवरण आधिकारिक अभिलेख से सत्यापित करें।',
  },
  mr: {
    officeHeader: 'जिल्हाधिकारी कार्यालय',
    section11Title: 'कलम 11 अंतर्गत अधिसूचना',
    awardTitle: 'पुरस्कार सूचना',
    ownerLabel: 'मालक',
    surveyLabel: 'सर्वे क्रमांक',
    villageLabel: 'गाव',
    tehsilLabel: 'तालुका',
    districtLabel: 'जिल्हा',
    projectLabel: 'प्रकल्प',
    areaLabel: 'क्षेत्रफळ',
    compensationAssessedLabel: 'अंदाजित मोबदला',
    compensationPaidLabel: 'दिलेला मोबदला',
    dateLabel: 'दिनांक',
    qrCaption: 'तुमच्या प्रकरणाची स्थिती ऑनलाइन पाहण्यासाठी हा कोड स्कॅन करा',
    signatureLabel: 'जारी करणाऱ्या अधिकाऱ्याची स्वाक्षरी व शिक्का',
    disclaimer:
      'हे BhoomiSetu प्रोटोटाइपद्वारे प्रात्यक्षिकासाठी तयार केले आहे. विश्वास ठेवण्यापूर्वी सर्व तपशील अधिकृत नोंदीशी पडताळून पाहा.',
  },
  gu: {
    officeHeader: 'જિલ્લા કલેક્ટર કચેરી',
    section11Title: 'કલમ 11 હેઠળ સૂચના',
    awardTitle: 'પુરસ્કાર જાણ',
    ownerLabel: 'માલિક',
    surveyLabel: 'સર્વે નંબર',
    villageLabel: 'ગામ',
    tehsilLabel: 'તાલુકો',
    districtLabel: 'જિલ્લો',
    projectLabel: 'પ્રોજેક્ટ',
    areaLabel: 'વિસ્તાર',
    compensationAssessedLabel: 'આકારેલું વળતર',
    compensationPaidLabel: 'ચૂકવેલું વળતર',
    dateLabel: 'તારીખ',
    qrCaption: 'તમારા કેસની સ્થિતિ ઓનલાઇન જોવા માટે આ કોડ સ્કેન કરો',
    signatureLabel: 'જારી કરનાર અધિકારીની સહી અને સિક્કો',
    disclaimer:
      'આ BhoomiSetu પ્રોટોટાઇપ દ્વારા નિદર્શન માટે બનાવવામાં આવ્યું છે. વિશ્વાસ કરતા પહેલા બધી વિગતો સત્તાવાર રેકોર્ડ સાથે ચકાસો.',
  },
  te: {
    officeHeader: 'జిల్లా కలెక్టర్ కార్యాలయం',
    section11Title: 'సెక్షన్ 11 కింద నోటిఫికేషన్',
    awardTitle: 'అవార్డు సమాచారం',
    ownerLabel: 'యజమాని',
    surveyLabel: 'సర్వే నంబర్',
    villageLabel: 'గ్రామం',
    tehsilLabel: 'తహసీల్',
    districtLabel: 'జిల్లా',
    projectLabel: 'ప్రాజెక్ట్',
    areaLabel: 'విస్తీర్ణం',
    compensationAssessedLabel: 'అంచనా వేసిన పరిహారం',
    compensationPaidLabel: 'చెల్లించిన పరిహారం',
    dateLabel: 'తేదీ',
    qrCaption: 'మీ కేసు స్థితిని ఆన్‌లైన్‌లో చూడటానికి ఈ కోడ్‌ను స్కాన్ చేయండి',
    signatureLabel: 'జారీ చేసిన అధికారి సంతకం మరియు ముద్ర',
    disclaimer:
      'ఇది ప్రదర్శన కోసం BhoomiSetu ప్రోటోటైప్ ద్వారా రూపొందించబడింది. ఆధారపడే ముందు అన్ని వివరాలను అధికారిక రికార్డుతో ధృవీకరించండి.',
  },
  ta: {
    officeHeader: 'மாவட்ட ஆட்சியர் அலுவலகம்',
    section11Title: 'பிரிவு 11-ன் கீழ் அறிவிப்பு',
    awardTitle: 'விருது அறிவிப்பு',
    ownerLabel: 'உரிமையாளர்',
    surveyLabel: 'சர்வே எண்',
    villageLabel: 'கிராமம்',
    tehsilLabel: 'தாலுகா',
    districtLabel: 'மாவட்டம்',
    projectLabel: 'திட்டம்',
    areaLabel: 'பரப்பளவு',
    compensationAssessedLabel: 'மதிப்பிடப்பட்ட இழப்பீடு',
    compensationPaidLabel: 'செலுத்தப்பட்ட இழப்பீடு',
    dateLabel: 'தேதி',
    qrCaption: 'உங்கள் வழக்கின் நிலையை ஆன்லைனில் காண இந்த குறியீட்டை ஸ்கேன் செய்யவும்',
    signatureLabel: 'வழங்கும் அதிகாரியின் கையொப்பம் மற்றும் முத்திரை',
    disclaimer:
      'இது காட்சிக்காக BhoomiSetu முன்மாதிரி மூலம் உருவாக்கப்பட்டது. நம்பிக்கை வைப்பதற்கு முன் அனைத்து விவரங்களையும் அதிகாரப்பூர்வ பதிவுடன் சரிபார்க்கவும்.',
  },
  kn: {
    officeHeader: 'ಜಿಲ್ಲಾಧಿಕಾರಿ ಕಚೇರಿ',
    section11Title: 'ಸೆಕ್ಷನ್ 11ರ ಅಡಿಯಲ್ಲಿ ಅಧಿಸೂಚನೆ',
    awardTitle: 'ಪ್ರಶಸ್ತಿ ಸೂಚನೆ',
    ownerLabel: 'ಮಾಲೀಕ',
    surveyLabel: 'ಸರ್ವೆ ಸಂಖ್ಯೆ',
    villageLabel: 'ಗ್ರಾಮ',
    tehsilLabel: 'ತಾಲೂಕು',
    districtLabel: 'ಜಿಲ್ಲೆ',
    projectLabel: 'ಯೋಜನೆ',
    areaLabel: 'ವಿಸ್ತೀರ್ಣ',
    compensationAssessedLabel: 'ಅಂದಾಜು ಪರಿಹಾರ',
    compensationPaidLabel: 'ಪಾವತಿಸಿದ ಪರಿಹಾರ',
    dateLabel: 'ದಿನಾಂಕ',
    qrCaption: 'ನಿಮ್ಮ ಪ್ರಕರಣದ ಸ್ಥಿತಿಯನ್ನು ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ವೀಕ್ಷಿಸಲು ಈ ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    signatureLabel: 'ಹೊರಡಿಸುವ ಅಧಿಕಾರಿಯ ಸಹಿ ಮತ್ತು ಮುದ್ರೆ',
    disclaimer:
      'ಇದನ್ನು ಪ್ರದರ್ಶನಕ್ಕಾಗಿ BhoomiSetu ಪ್ರೋಟೋಟೈಪ್ ಮೂಲಕ ರಚಿಸಲಾಗಿದೆ. ಅವಲಂಬಿಸುವ ಮೊದಲು ಎಲ್ಲಾ ವಿವರಗಳನ್ನು ಅಧಿಕೃತ ದಾಖಲೆಯೊಂದಿಗೆ ಪರಿಶೀಲಿಸಿ.',
  },
  bn: {
    officeHeader: 'জেলা কালেক্টর কার্যালয়',
    section11Title: 'ধারা ১১ অনুযায়ী বিজ্ঞপ্তি',
    awardTitle: 'পুরস্কার বিজ্ঞপ্তি',
    ownerLabel: 'মালিক',
    surveyLabel: 'সার্ভে নম্বর',
    villageLabel: 'গ্রাম',
    tehsilLabel: 'তহশিল',
    districtLabel: 'জেলা',
    projectLabel: 'প্রকল্প',
    areaLabel: 'আয়তন',
    compensationAssessedLabel: 'নির্ধারিত ক্ষতিপূরণ',
    compensationPaidLabel: 'প্রদত্ত ক্ষতিপূরণ',
    dateLabel: 'তারিখ',
    qrCaption: 'আপনার মামলার অবস্থা অনলাইনে দেখতে এই কোডটি স্ক্যান করুন',
    signatureLabel: 'প্রদানকারী কর্মকর্তার স্বাক্ষর ও সিল',
    disclaimer:
      'এটি প্রদর্শনের জন্য BhoomiSetu প্রোটোটাইপ দ্বারা তৈরি করা হয়েছে। নির্ভর করার আগে সমস্ত বিবরণ সরকারি রেকর্ডের সাথে যাচাই করুন।',
  },
  or: {
    officeHeader: 'ଜିଲ୍ଲା କାଲେକ୍ଟର କାର୍ଯ୍ୟାଳୟ',
    section11Title: 'ଧାରା 11 ଅନୁଯାୟୀ ବିଜ୍ଞପ୍ତି',
    awardTitle: 'ପୁରସ୍କାର ସୂଚନା',
    ownerLabel: 'ମାଲିକ',
    surveyLabel: 'ସର୍ଭେ ନମ୍ବର',
    villageLabel: 'ଗାଁ',
    tehsilLabel: 'ତହସିଲ',
    districtLabel: 'ଜିଲ୍ଲା',
    projectLabel: 'ପ୍ରକଳ୍ପ',
    areaLabel: 'କ୍ଷେତ୍ରଫଳ',
    compensationAssessedLabel: 'ମୂଲ୍ୟାୟିତ କ୍ଷତିପୂରଣ',
    compensationPaidLabel: 'ପ୍ରଦତ୍ତ କ୍ଷତିପୂରଣ',
    dateLabel: 'ତାରିଖ',
    qrCaption: 'ଆପଣଙ୍କ କେସର ସ୍ଥିତି ଅନଲାଇନରେ ଦେଖିବାକୁ ଏହି କୋଡ୍ ସ୍କାନ୍ କରନ୍ତୁ',
    signatureLabel: 'ଜାରୀକାରୀ ଅଧିକାରୀଙ୍କ ହସ୍ତାକ୍ଷର ଏବଂ ମୋହର',
    disclaimer:
      'ଏହା ପ୍ରଦର୍ଶନ ପାଇଁ BhoomiSetu ପ୍ରୋଟୋଟାଇପ୍ ଦ୍ୱାରା ତିଆରି ହୋଇଛି। ନିର୍ଭର କରିବା ପୂର୍ବରୁ ସମସ୍ତ ବିବରଣୀ ସରକାରୀ ରେକର୍ଡ ସହିତ ଯାଞ୍ଚ କରନ୍ତୁ।',
  },
  pa: {
    officeHeader: 'ਜ਼ਿਲ੍ਹਾ ਕਲੈਕਟਰ ਦਫ਼ਤਰ',
    section11Title: 'ਧਾਰਾ 11 ਅਧੀਨ ਸੂਚਨਾ',
    awardTitle: 'ਪੁਰਸਕਾਰ ਸੂਚਨਾ',
    ownerLabel: 'ਮਾਲਕ',
    surveyLabel: 'ਸਰਵੇ ਨੰਬਰ',
    villageLabel: 'ਪਿੰਡ',
    tehsilLabel: 'ਤਹਿਸੀਲ',
    districtLabel: 'ਜ਼ਿਲ੍ਹਾ',
    projectLabel: 'ਪ੍ਰੋਜੈਕਟ',
    areaLabel: 'ਖੇਤਰਫਲ',
    compensationAssessedLabel: 'ਮੁਲਾਂਕਿਤ ਮੁਆਵਜ਼ਾ',
    compensationPaidLabel: 'ਅਦਾ ਕੀਤਾ ਮੁਆਵਜ਼ਾ',
    dateLabel: 'ਮਿਤੀ',
    qrCaption: 'ਆਪਣੇ ਕੇਸ ਦੀ ਸਥਿਤੀ ਆਨਲਾਈਨ ਵੇਖਣ ਲਈ ਇਹ ਕੋਡ ਸਕੈਨ ਕਰੋ',
    signatureLabel: 'ਜਾਰੀ ਕਰਨ ਵਾਲੇ ਅਧਿਕਾਰੀ ਦੇ ਦਸਤਖਤ ਅਤੇ ਮੋਹਰ',
    disclaimer:
      'ਇਹ ਪ੍ਰਦਰਸ਼ਨ ਲਈ BhoomiSetu ਪ੍ਰੋਟੋਟਾਈਪ ਦੁਆਰਾ ਤਿਆਰ ਕੀਤਾ ਗਿਆ ਹੈ। ਭਰੋਸਾ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਸਾਰੇ ਵੇਰਵਿਆਂ ਦੀ ਅਧਿਕਾਰਤ ਰਿਕਾਰਡ ਨਾਲ ਪੁਸ਼ਟੀ ਕਰੋ।',
  },
};

const SECTION_11_BODY: Record<SmsOwnerLanguage, BodyTemplate> = {
  en: (p) =>
    `Notice is hereby given that land bearing Survey No. ${p.surveyNumber} at ${p.village}, ${p.tehsil}, ${p.district} is proposed to be acquired for the project "${p.projectName}". Objections, if any, may be filed at the office noted above within the prescribed period.`,
  hi: (p) =>
    `सूचित किया जाता है कि सर्वे नंबर ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} स्थित भूमि को परियोजना "${p.projectName}" के लिए अधिग्रहित किया जाना प्रस्तावित है। यदि कोई आपत्ति हो, तो निर्धारित अवधि के भीतर उपर्युक्त कार्यालय में दर्ज करें।`,
  mr: (p) =>
    `कळविण्यात येते की सर्वे क्रमांक ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} येथील जमीन प्रकल्प "${p.projectName}" साठी संपादित करण्याचे प्रस्तावित आहे. काही आक्षेप असल्यास विहित मुदतीत वरील कार्यालयात नोंदवावा.`,
  gu: (p) =>
    `જાણ કરવામાં આવે છે કે સર્વે નંબર ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} ખાતેની જમીન પ્રોજેક્ટ "${p.projectName}" માટે સંપાદિત કરવાની દરખાસ્ત છે. કોઈ વાંધો હોય તો નિયત સમયમર્યાદામાં ઉપરોક્ત કચેરીમાં નોંધાવો.`,
  te: (p) =>
    `సర్వే నంబర్ ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} వద్ద ఉన్న భూమిని "${p.projectName}" ప్రాజెక్ట్ కోసం సేకరించనున్నట్లు తెలియజేయడమైనది. ఏదైనా అభ్యంతరం ఉంటే నిర్దేశిత గడువులోగా పై కార్యాలయంలో దాఖలు చేయవచ్చు.`,
  ta: (p) =>
    `சர்வே எண் ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} இல் உள்ள நிலம் "${p.projectName}" திட்டத்திற்காக கையகப்படுத்தப்பட உள்ளது என அறிவிக்கப்படுகிறது. ஏதேனும் ஆட்சேபனை இருந்தால் மேற்கண்ட அலுவலகத்தில் குறிப்பிட்ட காலத்திற்குள் தெரிவிக்கவும்.`,
  kn: (p) =>
    `ಸರ್ವೆ ಸಂಖ್ಯೆ ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} ನಲ್ಲಿರುವ ಭೂಮಿಯನ್ನು "${p.projectName}" ಯೋಜನೆಗಾಗಿ ಸ್ವಾಧೀನಪಡಿಸಿಕೊಳ್ಳಲು ಪ್ರಸ್ತಾಪಿಸಲಾಗಿದೆ ಎಂದು ತಿಳಿಸಲಾಗಿದೆ. ಯಾವುದೇ ಆಕ್ಷೇಪಣೆ ಇದ್ದರೆ ನಿಗದಿತ ಅವಧಿಯೊಳಗೆ ಮೇಲಿನ ಕಚೇರಿಯಲ್ಲಿ ಸಲ್ಲಿಸಬಹುದು.`,
  bn: (p) =>
    `জানানো যাচ্ছে যে সার্ভে নম্বর ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} স্থিত জমি "${p.projectName}" প্রকল্পের জন্য অধিগ্রহণের প্রস্তাব করা হয়েছে। কোনো আপত্তি থাকলে নির্ধারিত সময়ের মধ্যে উপরোক্ত কার্যালয়ে জানান।`,
  or: (p) =>
    `ଜଣାଇ ଦିଆଯାଉଛି ଯେ ସର୍ଭେ ନମ୍ବର ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} ସ୍ଥିତ ଜମି "${p.projectName}" ପ୍ରକଳ୍ପ ପାଇଁ ଅଧିଗ୍ରହଣ କରାଯିବାକୁ ପ୍ରସ୍ତାବିତ। କୌଣସି ଆପତ୍ତି ଥିଲେ ନିର୍ଦ୍ଧାରିତ ସମୟସୀମା ମଧ୍ୟରେ ଉପରୋକ୍ତ କାର୍ଯ୍ୟାଳୟରେ ଦାଖଲ କରନ୍ତୁ।`,
  pa: (p) =>
    `ਸੂਚਿਤ ਕੀਤਾ ਜਾਂਦਾ ਹੈ ਕਿ ਸਰਵੇ ਨੰਬਰ ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} ਵਿਖੇ ਸਥਿਤ ਜ਼ਮੀਨ ਨੂੰ "${p.projectName}" ਪ੍ਰੋਜੈਕਟ ਲਈ ਗ੍ਰਹਿਣ ਕਰਨ ਦਾ ਪ੍ਰਸਤਾਵ ਹੈ। ਜੇਕਰ ਕੋਈ ਇਤਰਾਜ਼ ਹੋਵੇ ਤਾਂ ਨਿਰਧਾਰਤ ਸਮੇਂ ਅੰਦਰ ਉਪਰੋਕਤ ਦਫ਼ਤਰ ਵਿੱਚ ਦਰਜ ਕਰਵਾਓ।`,
};

const AWARD_BODY: Record<SmsOwnerLanguage, BodyTemplate> = {
  en: (p) =>
    `An award has been passed for land bearing Survey No. ${p.surveyNumber} at ${p.village}, ${p.tehsil}, ${p.district} acquired for the project "${p.projectName}", with compensation of ₹${p.compensationEstimateText} assessed and ₹${p.compensationPaidText} paid as of ${p.referenceDate}.`,
  hi: (p) =>
    `परियोजना "${p.projectName}" के लिए अधिग्रहित सर्वे नंबर ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} स्थित भूमि हेतु पुरस्कार पारित किया गया है, जिसमें ₹${p.compensationEstimateText} का मुआवज़ा आकलित किया गया तथा दिनांक ${p.referenceDate} तक ₹${p.compensationPaidText} का भुगतान किया जा चुका है।`,
  mr: (p) =>
    `प्रकल्प "${p.projectName}" साठी संपादित सर्वे क्रमांक ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} येथील जमिनीसाठी पुरस्कार पारित करण्यात आला असून ₹${p.compensationEstimateText} मोबदला निश्चित करण्यात आला आहे व दिनांक ${p.referenceDate} पर्यंत ₹${p.compensationPaidText} अदा करण्यात आला आहे.`,
  gu: (p) =>
    `પ્રોજેક્ટ "${p.projectName}" માટે સંપાદિત સર્વે નંબર ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} ખાતેની જમીન માટે પુરસ્કાર પસાર કરવામાં આવ્યો છે, જેમાં ₹${p.compensationEstimateText} વળતર આકારવામાં આવ્યું અને તારીખ ${p.referenceDate} સુધીમાં ₹${p.compensationPaidText} ચૂકવવામાં આવ્યું છે.`,
  te: (p) =>
    `"${p.projectName}" ప్రాజెక్ట్ కోసం సేకరించిన సర్వే నంబర్ ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} భూమికి అవార్డు జారీ చేయబడింది, ₹${p.compensationEstimateText} పరిహారం అంచనా వేయబడింది మరియు ${p.referenceDate} నాటికి ₹${p.compensationPaidText} చెల్లించబడింది.`,
  ta: (p) =>
    `"${p.projectName}" திட்டத்திற்காக கையகப்படுத்தப்பட்ட சர்வே எண் ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} நிலத்திற்கான விருது வழங்கப்பட்டுள்ளது, ₹${p.compensationEstimateText} இழப்பீடு மதிப்பிடப்பட்டு ${p.referenceDate} வரை ₹${p.compensationPaidText} செலுத்தப்பட்டுள்ளது.`,
  kn: (p) =>
    `"${p.projectName}" ಯೋಜನೆಗಾಗಿ ಸ್ವಾಧೀನಪಡಿಸಿಕೊಂಡ ಸರ್ವೆ ಸಂಖ್ಯೆ ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} ಭೂಮಿಗೆ ಪ್ರಶಸ್ತಿ ಅಂಗೀಕರಿಸಲಾಗಿದೆ, ₹${p.compensationEstimateText} ಪರಿಹಾರ ಅಂದಾಜಿಸಲಾಗಿದ್ದು ${p.referenceDate} ರವರೆಗೆ ₹${p.compensationPaidText} ಪಾವತಿಸಲಾಗಿದೆ.`,
  bn: (p) =>
    `"${p.projectName}" প্রকল্পের জন্য অধিগ্রহণকৃত সার্ভে নম্বর ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} জমির জন্য পুরস্কার পাশ করা হয়েছে, যাতে ₹${p.compensationEstimateText} ক্ষতিপূরণ নির্ধারণ করা হয়েছে এবং ${p.referenceDate} পর্যন্ত ₹${p.compensationPaidText} প্রদান করা হয়েছে।`,
  or: (p) =>
    `"${p.projectName}" ପ୍ରକଳ୍ପ ପାଇଁ ଅଧିଗ୍ରହଣ ହୋଇଥିବା ସର୍ଭେ ନମ୍ବର ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} ଜମି ପାଇଁ ପୁରସ୍କାର ପାରିତ ହୋଇଛି, ଯେଉଁଥିରେ ₹${p.compensationEstimateText} କ୍ଷତିପୂରଣ ମୂଲ୍ୟାୟନ କରାଯାଇଛି ଏବଂ ${p.referenceDate} ସୁଦ୍ଧା ₹${p.compensationPaidText} ପ୍ରଦାନ କରାଯାଇଛି।`,
  pa: (p) =>
    `"${p.projectName}" ਪ੍ਰੋਜੈਕਟ ਲਈ ਗ੍ਰਹਿਣ ਕੀਤੀ ਸਰਵੇ ਨੰਬਰ ${p.surveyNumber}, ${p.village}, ${p.tehsil}, ${p.district} ਜ਼ਮੀਨ ਲਈ ਪੁਰਸਕਾਰ ਪਾਸ ਕੀਤਾ ਗਿਆ ਹੈ, ਜਿਸ ਵਿੱਚ ₹${p.compensationEstimateText} ਮੁਆਵਜ਼ਾ ਮੁਲਾਂਕਿਤ ਕੀਤਾ ਗਿਆ ਅਤੇ ${p.referenceDate} ਤੱਕ ₹${p.compensationPaidText} ਅਦਾ ਕੀਤਾ ਜਾ ਚੁੱਕਾ ਹੈ।`,
};

export type NoticeContent = {
  labels: NoticeLabels;
  title: string;
  body: string;
};

// Builds the printable notice's translated labels, title and body sentence
// for the given notice type and the owner's own preferred language — never
// the signed-in official's UI language. Deterministic, no network call, same
// discipline as `buildSmsPreview`.
export function buildNoticeContent(type: NoticeType, language: SmsOwnerLanguage, params: NoticeParams): NoticeContent {
  const labels = LABELS[language];
  const title = type === 'section_11' ? labels.section11Title : labels.awardTitle;
  const body = (type === 'section_11' ? SECTION_11_BODY : AWARD_BODY)[language](params);
  return { labels, title, body };
}
